import Link from "next/link";
import { ArrowUpRight, Clock3, ShieldAlert, UsersRound } from "lucide-react";
import { AdminShell } from "@/components/admin/admin-shell";
import { CategoryBreakdown, VolumeChart } from "@/components/admin/admin-charts";
import { dataAdapter } from "@/lib/data";

export default async function AdminOverviewPage() {
  const [metrics, resolutions, users, transactions] = await Promise.all([dataAdapter.getMetrics(), dataAdapter.getResolutionQueue(), dataAdapter.getUsers(), dataAdapter.getTransactions()]);
  return <AdminShell title="Overview" description="Platform health, market operations and settlement activity." actions={<button className="primary-button compact">Create market</button>}>
    <div className="admin-metric-grid">{metrics.map((metric, index) => <article key={metric.label}><div><span>{metric.label}</span>{index === 2 ? <UsersRound size={18} /> : index === 3 ? <ShieldAlert size={18} /> : <ArrowUpRight size={18} />}</div><strong>{metric.value}</strong><em className={metric.change >= 0 ? "positive" : "negative"}>{metric.change >= 0 ? "+" : ""}{metric.change}%</em><small>{metric.hint}</small></article>)}</div>
    <div className="admin-dashboard-grid"><VolumeChart /><CategoryBreakdown /></div>
    <div className="admin-dashboard-grid lower-grid"><section className="admin-panel"><div className="table-title"><div><h2>Resolution queue</h2><span>Markets requiring operational review</span></div><Link href="/admin/resolutions">View all</Link></div><div className="admin-list">{resolutions.slice(0, 4).map((item) => <article key={item.id}><span className={`status-dot-large ${item.status}`}><Clock3 size={15} /></span><div><strong>{item.market}</strong><small>{item.proposedOutcome} · {item.source}</small></div><span className={`status-pill ${item.status}`}>{item.status}</span></article>)}</div></section><section className="admin-panel"><div className="table-title"><div><h2>Risk review</h2><span>Accounts with elevated signals</span></div><Link href="/admin/users">View all</Link></div><div className="admin-list">{users.filter((user) => user.risk !== "low").map((user) => <article key={user.id}><span className="profile-avatar">{user.handle.slice(0, 2).toUpperCase()}</span><div><strong>@{user.handle}</strong><small>{user.wallet.slice(0, 10)}… · ${Math.round(user.volume / 1000)}K volume</small></div><span className={`risk-pill ${user.risk}`}>{user.risk}</span></article>)}</div></section></div>
    <section className="admin-panel transaction-preview"><div className="table-title"><div><h2>Recent transactions</h2><span>Latest indexed platform activity</span></div><Link href="/admin/transactions">View all</Link></div><div className="responsive-table"><table><thead><tr><th>Type</th><th>Wallet</th><th>Asset</th><th>Amount</th><th>Status</th><th>Time</th></tr></thead><tbody>{transactions.map((tx) => <tr key={tx.id}><td className="capitalize">{tx.type}</td><td className="mono">{tx.wallet}</td><td>{tx.asset}</td><td>${tx.amount.toLocaleString()}</td><td><span className={`status-pill ${tx.status}`}>{tx.status}</span></td><td>{tx.time}</td></tr>)}</tbody></table></div></section>
  </AdminShell>;
}
