"use client";

import { Bell, ChevronRight, Copy, Globe2, KeyRound, LogOut, ShieldCheck, SlidersHorizontal, WalletCards } from "lucide-react";
import { SiteShell } from "@/components/site-shell";
import { AccountShell } from "@/components/account-shell";
import { useApp } from "@/components/app-provider";
import { shortAddress } from "@/lib/format";

export default function SettingsPage() {
  const { walletAddress, connected, setWalletOpen, disconnectWallet, notify } = useApp();
  return <SiteShell><div className="page-container inner-page"><AccountShell title="Settings" eyebrow="Account" description="Manage wallet, notifications and interface preferences."><div className="settings-grid"><section className="settings-card"><div className="settings-card-head"><span className="settings-icon"><WalletCards size={18} /></span><div><h2>Connected wallet</h2><p>Primary account used for trading and funding.</p></div></div><div className="connected-wallet-row"><span className="wallet-mark">BW</span><div><strong>{connected ? shortAddress(walletAddress) : "No wallet connected"}</strong><small>{connected ? "Polygon · Connected" : "Connect a supported crypto wallet"}</small></div>{connected ? <><button className="icon-button" aria-label="Copy wallet address" onClick={() => notify("Address copied")}><Copy size={16} /></button><button className="text-button danger" onClick={disconnectWallet}><LogOut size={15} />Disconnect</button></> : <button className="primary-button compact" onClick={() => setWalletOpen(true)}>Connect</button>}</div></section><section className="settings-card"><div className="settings-card-head"><span className="settings-icon"><Bell size={18} /></span><div><h2>Notifications</h2><p>Choose which market and account events reach you.</p></div></div>{["Order filled or partially filled", "Market nearing resolution", "Large probability movement", "Funding confirmation"].map((label, index) => <label className="setting-toggle" key={label}><span>{label}<small>{index === 2 ? "Movement above your configured threshold" : "In-app notifications"}</small></span><input type="checkbox" defaultChecked={index !== 2} /><i /></label>)}</section><section className="settings-card"><div className="settings-card-head"><span className="settings-icon"><SlidersHorizontal size={18} /></span><div><h2>Trading preferences</h2><p>Defaults used when opening a market ticket.</p></div></div>{[{ icon: KeyRound, title: "Default order type", value: "Market" }, { icon: Globe2, title: "Display currency", value: "USD" }, { icon: ShieldCheck, title: "Slippage warning", value: "1.0%" }].map(({ icon: Icon, title, value }) => <button className="settings-row" key={title}><Icon size={17} /><span>{title}</span><em>{value}</em><ChevronRight size={16} /></button>)}</section></div></AccountShell></div></SiteShell>;
}
